name: 'server-build'

on:
  push:
    branches:
      - 'server-build'

permissions:
    contents: write

jobs:
    build:
      name: building executable
      runs-on: ['ubuntu-latest']
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry 
            poetry install

        - name: Regression Test
          run: pytest __test__/test_regression

        - name: Build Generation
          run: pyinstaller starter.spec

        - name: Testing the build
          run: pytest __test__/test_sanity

        - name: Upload Executable
          uses: actions/upload-artifact@v3
          with:
            name: linux
            path: dist/graspit
            retention-days: 5

    release:
      name: Preparing Inital release
      runs-on: 'windows-latest'
      needs: build
      permissions: read-all

      steps:
        - name: Reading Version
          uses: SebRollen/toml-action@v1.0.2
          id: read_version
          with:
            file: 'pyproject.toml'
            field: 'tools.poetry.version'

        - name: Generate a Release
          uses: ncipollo/release-action@v1
          with:
#            tag: steps.read_version.outputs.value
            allowUpdates: true
            artifactErrorsFailBuild: true
            artifacts: "release.tar.gz,foo/*.txt"
            body: "Nightly Pre-Release for the graspit"
            commit: true
            tag: 0.0.1
