name: 'server-build'

on:
  push:
    branches:
      - 'server-build'

permissions:
    contents: write

jobs:
    build:
      name: building executable
      runs-on: ['ubuntu-latest', 'macos-latest', 'windows-latest']
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry 
            poetry install

        - name: Testing Application
          run: pytest __test__/test_regression

        - name: build executable
          run: pyinstaller starter.spec

        - name: testing the build
          run: pytest __test__/test_sanity
