name: 'server-build'

on:
  push:
    branches:
      - 'server-build'

permissions:
    contents: write

jobs:
    build:
      name: building executable
      strategy:
        matrix:
          os: ['macos-latest', 'windows-latest', 'ubuntu-latest']


      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry 
            poetry install

        - name: Regression Test
          run: pytest __test__/test_regression

        - name: Build Generation
          run: pyinstaller starter.spec

        - name: Testing the build
          run: pytest __test__/test_sanity

        - name: Upload Executable
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.os }}
            path: dist/*
            retention-days: 1

    release:
      name: Preparing Initial release
      runs-on: 'ubuntu-latest'
      needs: build
      permissions: write-all

      steps:
        - uses: actions/checkout@v3
        - uses: actions/download-artifact@v3
          with:
            path: dist

        - name: Release Prep
          id: version
          run: |
            bash ./.github/scripts/fetch-server-version.sh

        - uses: softprops/action-gh-release@v1
          id: release
          with:
            files: dist/**/*
            body: ":rocket: bump server release version to `${{ steps.version.outputs.VERSION }}"
            prerelease: true
            tag_name: ${{ steps.version.outputs.VERSION }}
            name: ${{ steps.version.outputs.VERSION }}

        - name: Post Release Post
          run: bash ./.github/scripts/release-server-tag.sh

        - name: Request dashboard-build to use the latest release
          uses: peter-evans/create-pull-request@v5
          with:
            commit-message: "Requesting to use the new build for the server: ${{ steps.version.outputs.VERSION }}"
            delete-branch: true
            title: "Bump Server Build"
            labels: "Automated,Server-build"
            reviewers: "RahulARanger"
            body: ":rocket: bump release version to `${{ steps.version.outputs.VERSION }}`. 
:magic_wand: make sure to edit this [release](${{ steps.release.outputs.url }}) once done."
            base: "dashboard-build"
            assignees: "RahulARanger"
