name: 'dashboard-build'

on:
  push:
    branches:
      - 'dashboard-build'

permissions:
    contents: write

jobs:

    release:
      name: Preparing pre-release
      runs-on: 'ubuntu-latest'
      permissions: write-all

      steps:

        - uses: actions/checkout@v3
        - name: Upload Executable
          uses: actions/upload-artifact@v3
          with:
            name: read
            path: README.md
            retention-days: 1
        - uses: actions/download-artifact@v3
          with:
            path: dist

        - name: Release Prep
          id: version
          run: |
            bash ./.github/scripts/fetch-server-version.sh

        - uses: softprops/action-gh-release@v1
          id: release
          with:
            files: dist/**/*
            body: ":rocket: bump server release version to `${{ steps.version.outputs.VERSION }}`"
            prerelease: true
            tag_name: ${{ steps.version.outputs.VERSION }}
            name: ${{ steps.version.outputs.VERSION }}

        - name: Post Release Post
          run: bash ./.github/scripts/release-server-tag.sh

        - name: Request dashboard-build to use the latest release
          uses: peter-evans/create-pull-request@v5
          with:
            commit-message: "Requesting to use the new build for the server: ${{ steps.version.outputs.VERSION }}"
            delete-branch: true
            title: "Bump Server Build"
            labels: "Automated,Server-build"
            reviewers: "RahulARanger"
            body: ":rocket: bump release version to `${{ steps.version.outputs.VERSION }}`. 
:magic_wand: make sure to edit this [release](${{ steps.release.outputs.url }}) once done."
            base: "dashboard-build"
            assignees: "RahulARanger"
