name: 'server-build'

on:
  push:
    branches:
      - 'server-build'

permissions:
    contents: write

jobs:
    build:
      name: building executable
      strategy:
        matrix:
          os: ['macos-latest', 'windows-latest', 'ubuntu-latest']


      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry 
            poetry install

        - name: Regression Test
          run: pytest __test__/test_regression

        - name: Build Generation
          run: pyinstaller starter.spec

        - name: Testing the build
          run: pytest __test__/test_sanity

        - name: Upload Executable
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.os }}
            path: dist/*
            retention-days: 1

    release:
      name: Preparing Inital release
      runs-on: 'ubuntu-latest'
      needs: build
      permissions:
        contents: write

      steps:
        - uses: actions/download-artifact@v3
          with:
            path: dist

        - uses: softprops/action-gh-release@v1
          with:
            files: dist/**/*
            body: "Nightly Pre-Release for the graspit"
            prerelease: true
            tag_name: "0.12.0"
            name: "0.12.0"
