name: 'server-build'

on:
  push:
    branches:
      - 'server-build'

permissions:
    contents: write

jobs:
    build:
      name: building executable
      strategy:
        matrix:
          os: ['macos-latest', 'windows-latest', 'ubuntu-latest']


      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install poetry 
            poetry install

        - name: Regression Test
          run: pytest __test__/test_regression

        - name: Build Generation
          run: pyinstaller starter.spec

        - name: Testing the build
          run: pytest __test__/test_sanity

        - name: Upload Executable
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.os }}
            path: dist/*
            retention-days: 1

    release:
      name: Preparing Initial release
      runs-on: 'ubuntu-latest'
      needs: build
      permissions:
        contents: write

      steps:
        - uses: actions/download-artifact@v3
          with:
            path: dist

        - name: Communicate the Release
          id: version
          run: |
            bash ./.github/scripts/pin-server-tag.sh

        - name: Read the Release
          run: echo ${{ steps.version.outputs.VERSION }}

        - uses: softprops/action-gh-release@v1
          with:
            files: dist/**/*
            body: "PreR"
            prerelease: true
            tag_name: ${{ steps.version.outputs.VERSION }}
            name: ${{ steps.version.outputs.VERSION }}

        - name: Request dashboard-build to use the latest release
          uses: peter-evans/create-pull-request@v5
          with:
            commit-message: "Requesting to use the new build for the server: ${{ steps.version.outputs.VERSION }}"
            delete-branch: true
            branch-suffix: "server-build"
            title: "Bump Server Build"
            labels: "Automated,Server-build"
            reviewers: "RahulARanger"
            base: "dashboard-build"
            assignees: "RahulARanger"
